<?php

namespace AppBundle\Repository;

use \DateTime;

use Doctrine\ORM\Query\Expr\Join;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
     public function showAllByDate()
    {
            return $this->createQueryBuilder('b')

            ->orderBy('b.creationDate','DESC')
            ->getQuery()
            ->getResult();
    }

    public function bookingsPerClientPerMonth($client)
    {
        return $this->createQueryBuilder('b')
            ->innerJoin('b.client', 'cl', Join::WITH, 'b.client = cl.id')
            ->select('cl.lastName')
            ->where('b.client = :client')
            ->andWhere('b.creationDate BETWEEN :from AND :to')
            ->setParameter('client', $client)
            ->setParameter('from',new \DateTime('-30 days'), \Doctrine\DBAL\Types\Type::DATETIME)
            ->setParameter('to', new \DateTime()) 
            ->getQuery()
            ->getResult();
    }

   
}


