<?php

namespace AppBundle\Repository;



/**
 * CarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRepository extends \Doctrine\ORM\EntityRepository
{   

    public function findAllXWing()
    {
        return $this->createQueryBuilder('c')
            ->where('c.carRange = :carRange')
            ->setParameter('carRange', 1)
            ->getQuery()
            ->getResult();
    }


    public function showXWingAvailable()
    {
        return $this->createQueryBuilder('c')
            ->select('count(c.name)')
            ->where('c.carRange = :carRange')
            ->andWhere('c.available = :available')
            ->setParameter('carRange', 1)
            ->setParameter('available', 1)
            ->getQuery()
            ->getSingleScalarResult();
    }


    public function findAllTieFighter()
    {
        return $this->createQueryBuilder('c')
            ->where('c.carRange = :carRange')
            ->setParameter('carRange', 2)
            ->getQuery()
            ->getResult();
    }

    public function showTieFighterAvailable()
    {
        return $this->createQueryBuilder('c')
            ->select('count(c.name)')
            ->where('c.carRange = :carRange')
            ->andWhere('c.available = :available')
            ->setParameter('carRange', 2)
            ->setParameter('available', 1)
            ->getQuery()
            ->getSingleScalarResult();
    }

}