<?php

namespace AppBundle\Repository;

/**
 * CarRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarRangeRepository extends \Doctrine\ORM\EntityRepository
{


}
